### ISSUE TITLE
Upgrade to SBT 0.13.13 and profit from performance improvements

### ISSUE THREAD

**Issue by retronym** [typesafehub/zinc#105]
https://github.com/sbt/sbt/pull/2754 offers a way to cache the classloader that contains the incremental compiler, rather than creating a new one each time. This can deliver significant performance improvements due to the way that JIT works.

 - [x] Update to SBT 0.13.13
 - [x] Use the new method `AnalyzingCompiler#withClassLoaderCache` to enable the new classloader recycling.
 - [ ] Verify that new instances of `xsbt.CallbackGlobal` are not classloaded in the steady state (`java -verbose:class` should stop logging.)

**Comment by gslowikowski** [comment]
Just a note about SBT Compiler Maven Plugin - I'm [cache'ing classloaders](https://github.com/sbt-compiler-maven-plugin/sbt-compiler-maven-plugin/blob/sbt-compiler-1.0.0-beta9/sbt-compiler-maven-plugin/src/main/java/com/google/code/sbt/compiler/plugin/AbstractSBTCompileMojo.java#L745) (on different level) since [over 2 years](https://github.com/sbt-compiler-maven-plugin/sbt-compiler-maven-plugin/commit/58d08e1deeba63faad856562b488382277196517) and it works great in multi-module builds :)

In my case the main reason was to cache Sala classes. I wonder, if your new feature will improve performance even more. When will you release Zinc 0.3.13?

**Comment by retronym** [comment]
Fixed in #105

**Comment by retronym** [comment]
Hi @gslowikowski,

It is certainly possible that you're already cached away from this bug in the maven plugin. You could test this out by adding `-verbose:class` to the compile server JVM you spawn and checking that:

```

**Comment by retronym** [comment]
@eed3si9n will have an idea timing of that release.

**Comment by eed3si9n** [comment]
http://downloads.typesafe.com/zinc/0.3.13/zinc-0.3.13.tgz is out.
